# Generated by Django 5.2.1 on 2025-05-31 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNFE', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('Chartimg', models.ImageField(upload_to='image/')),
                ('logo', models.ImageField(upload_to='image/')),
                ('price', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
