# Generated by Django 5.2.1 on 2025-05-31 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNFE', '0003_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(upload_to='product/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
