# Generated by Django 5.2.1 on 2025-06-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPNFE', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
