# Generated by Django 5.2.1 on 2025-07-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPNFE', '0006_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
