# Generated by Django 5.2.1 on 2025-07-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNFE', '0007_delete_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chart',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
