# Generated by Django 5.2.1 on 2025-07-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNFE', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ma_200',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='200-Day MA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='price_change_24h',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='24h Price Change (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='resistance_level',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='support_level',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='symbol',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='volume_24h',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='24h Trading Volume'),
            preserve_default=False,
        ),
    ]
