# Generated by Django 5.2.1 on 2025-07-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPNFE', '0010_post_current_price_post_ma_200_post_price_change_24h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='franceDES',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='francePrice',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='franceTitle',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
