# Generated by Django 5.0.6 on 2025-07-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APPNFE", "0011_post_francedes_post_franceprice_post_francetitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="star",
            field=models.BooleanField(default=False),
        ),
    ]
